spring:
  application:
    name: hospital
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:hospital_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-hospital

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always