CREATE TABLE RESERVA (
    ID NUMBER PRIMARY KEY,
    FECHA_INICIO TIMESTAMP NOT NULL,
    FECHA_FIN TIMESTAMP NOT NULL,
    ID_HABITACION_SALA NUMBER NOT NULL,
    NOMBRE_CLIENTE VARCHAR2(100) NOT NULL,
    ESTADO_RESERVA VARCHAR2(50) NOT NULL
);

ALTER TABLE RESERVA ADD CONSTRAINT CHK_FECHAS CHECK (FECHA_INICIO < FECHA_FIN);

CREATE OR REPLACE TRIGGER TRG_VALIDAR_SOLAPAMIENTO
BEFORE INSERT OR UPDATE ON RESERVA
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM RESERVA
    WHERE ID_HABITACION_SALA = :NEW.ID_HABITACION_SALA
    AND ((:NEW.FECHA_INICIO BETWEEN FECHA_INICIO AND FECHA_FIN)
    OR (:NEW.FECHA_FIN BETWEEN FECHA_INICIO AND FECHA_FIN)
    OR (FECHA_INICIO BETWEEN :NEW.FECHA_INICIO AND :NEW.FECHA_FIN));

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Error: Solapamiento de reservas');
    END IF;
END;